street_abbrevs = {
    "al": "alley",
    "Assn": "Association",
    "av": "avenue",
    "bet": "between",
    "blk": "block",
    "boarding": "boarding house",
    "bl": "boulevard",
    "ch": "church",
    "cor": "corner",
    "ct": "court",
    "es": "east side",
    #    "n":"north"
    "nat": "national",
    #    "ne":"northeast",
    "nr": "near",
    # "ns":"north side"
    #   "nw":"northwest",
    "opr": "operator",
    "opp": "opposite",
    "pl": "place",
    "rd": "road",
    "sq": "square",
    "ss": "southside",
}


job_abbrevs = {
    "agt": "agent",
    "acct": "accountant",
    "asst": "assistant",
    "bartndr": "bartender",
    "bkbndr": "bookbinder",
    "bkpr": "bookkeeper",
    "blksmith": "blacksmith",
    "brklayr": "bricklayer",
    "B & L Assn": "Building & Loan Association",
    "cabinetmkr": "cabinetmaker",
    "capt": "captain",
    "car repr": "car repairer",
    "carp": "carpenter",
    "cash": "cashier",
    "cigarmkr": "cigarmaker",
    "civ engr": "civil engineer",
    "clk": "clerk",
    "clothingctr": "clothing cutter",
    "co": "company",
    "collr": "collector",
    "com mer": "commission merchant",
    "com trav": "commercial traveler",
    "condtr": "conductor",
    "confectr": "confectioner",
    "Cong": "Congregational",
    "con engr": "consulting engineer",
    "contrg": "contracting",
    "contr": "contractor",
    "dep": "deputy",
    "dept": "department",
    "dist": "district",
    "elect engr": "electrical engineer",
    "electro": "electrotyper",
    "elev opr": "elevator operator",
    "Epis": "Episcopal",
    "corres": "correspondent",
    "exch": "exchange",
    "express": "expressman",
    "fire dept": "fire department",
    "furng": "furnishing",
    "furnacemkr": "furnace maker",
    "furn rooms": "furnished rooms",
    "gasftr": "gas fitter",
    "harnessmkr": "harness maker",
    "int rev": "internal revenue",
    "ins": "insurance",
    "insp": "inspector",
    "inst": "instrument",
    "lab": "laborer",
    "lieut": "lieutenant",
    "lino": "linotype",
    "lithog": "lithographer",
    "Luth": "Lutheran",
    "meatmkt": "meatmarket",
    "mech engr": "mechanical engineer",
    "M E": "Methodist Episcopal",
    "milk": "milkman",
    "mngr": "manager",
    "mnfg": "manufacturing",
    "mnfr": "manufacturer",
    "mnfy": "manufactory",
    "mut": "mutual",
    "notary": "notary public",
    "PO": "post office",
    "paperctr": "paper cutter",
    "paperhr": "paperhanger",
    "phone opr": "telephone operator",
    "photog": "photographer",
    "police": "policeman",
    "pres": "president",
    "Presb": "Presbyterian",
    "prim": "primary",
    "prin": "principal",
    "prop": "proprietor",
    "pub": "publisher",
    "pub lib": "public library",
    "purch": "purchasing",
    "R C": "Roman Catholic",
    "real est": "real estate",
    "rec": "recieving",
    "Rev": "Reverend",
    # "S":"south",
    "schl": "school",
    "solcr": "solicitor",
    # "se":"southeast"
    "sec": "secretary",
    "shoemkr": "shoemaker",
    "stereo": "stereotyper",
    "stairbldr": "stairbuilder",
    "steamftr": "steamfitter",
    "stenog": "stenographer",
    "stk yds": "stock yards",
    "stonectr": "stone cutter",
    "supt": "superintendent",
    "tel opr": "telegraph operator",
    "trans": "transportation",
    "treas": "treasurer",
    "upholstr": "upholsterer",
    "vet surg": "veterinary surgeon",
    "v pres": "vice president",
    "whol": "wholesale",
    "wid": "widow",
    "wks": "works",
}

name_abbrevs = {
    "Chas": "Charles",
    "Wm": "William",
    "Jos": "Joseph",
    "Geo": "George",
    "Thos": "Thomas",
    "Robt": "Robert",
}
